name: "Build and deploy Github pages"
on:
  push:
    branches:
      - master

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 3.6

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pandas matplotlib seaborn sklearn
        pip install -U sphinx==2.2.0 sphinx-gallery==0.4.0 sphinx_bootstrap_theme numpydoc sphinxcontrib-bibtex
        pip install -e .

    - name: Build Sphinx Doc
        run: |
          make html

    - name: Deploy Github Pages
            uses: JamesIves/github-pages-deploy-action@3.5.9
            with:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              BRANCH: gh-pages
              FOLDER: docs/build/html/
